name: arf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pydantic>=2.0
  - pytest
  - pytest-asyncio
  - pytest-cov
  - pytest-timeout
  - pyyaml
  - cryptography                 
  - pip:
    - -e .                        # install the package in editable mode
